apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: xmpp
  name: xmpp
spec:
  ports:
  - name: 5222-5222
    port: 5222
    protocol: TCP
    targetPort: 5222
  selector:
    app: xmpp
  type: NodePort
status:
  loadBalancer: {}
